services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_final_for_quiz.py
    plan: free
    http:
      port: 80
